"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const { JSDOM } = require("jsdom");
const MiniSearch = require("minisearch");

const FIXTURE_SITE = path.join(__dirname, "..", "spec", "fixtures", "site");
const BASE_RUNTIME = fs.readFileSync(
    path.join(__dirname, "..", "assets", "client-search-base.js"),
    "utf8"
);
const ADAPTER_DIR = path.join(__dirname, "..", "assets", "adapters");

/**
 * Semantic search quality test — uses the REAL Ollama-generated index
 * with real embeddings to verify that the semantic adapter produces
 * correct search results for concept queries.
 *
 * This test loads a pre-built index that was generated by the Ruby
 * integration test (spec/ollama_integration_spec.rb) using a real
 * Ollama server with the embeddinggemma:300m model. The file contains:
 *   - documents: the full search index with real 768-dim embeddings
 *   - query_embeddings: pre-computed embeddings for concept queries
 *
 * The test runs these queries through the semantic adapter in jsdom
 * (the same code that runs in the browser) and verifies the results
 * match the expected articles.
 *
 * When the Ollama-generated index is not available (no Ollama server
 * was run), all tests are skipped. This is honest — we cannot test
 * semantic search quality without real embeddings.
 *
 * To generate the test data:
 *   OLLAMA_INTEGRATION=1 bundle exec rspec spec/ollama_integration_spec.rb
 */

const SEMANTIC_INDEX_PATH = path.join(FIXTURE_SITE, "_site", "search-index-semantic.json");

// Expected results — these are the golden standard. If the semantic
// adapter, cosine similarity, or result presentation changes, these
// tests will catch it. The expected titles are based on what the real
// embeddinggemma:300m model produces.
var EXPECTED_RESULTS = [
    {
        query: "preserving food without refrigeration",
        expectedInTop5: ["Fermentation in food processing"],
        description: "concept query → Fermentation article"
    },
    {
        query: "capturing images of the night sky",
        expectedInTop5: ["Astrophotography"],
        description: "concept query → Astrophotography article"
    },
    {
        query: "rope safety device for climbing",
        expectedInTop5: ["Belay device"],
        description: "concept query → Belay device article"
    },
    {
        query: "flatbread made with flour and water",
        expectedInTop5: ["Bread", "Pasta"],
        description: "concept query → Bread and Pasta articles"
    }
];

function loadSemanticIndex() {
    if (!fs.existsSync(SEMANTIC_INDEX_PATH)) {
        return null;
    }
    return JSON.parse(fs.readFileSync(SEMANTIC_INDEX_PATH, "utf8"));
}

function resultTitles(window) {
    return Array.from(window.document.querySelectorAll(".client-search-result h2"))
        .map(function (h2) { return h2.textContent; });
}

async function settle() {
    await new Promise(function (resolve) { setTimeout(resolve, 0); });
    await new Promise(function (resolve) { setTimeout(resolve, 0); });
}

function createSemanticWindow(semanticData, query) {
    var documents = semanticData.documents;
    var queryEmbedding = semanticData.query_embeddings[query];

    var dom = new JSDOM(
        `<!doctype html>
        <form id="search-form"><input id="search-query"><button>Search</button></form>
        <div id="search-status"></div><div id="search-results"></div>`,
        { url: `https://example.com/search/?q=${encodeURIComponent(query)}`, runScripts: "outside-only" }
    );

    // Provide the pre-computed query embedding — this is what
    // transformers.js would produce in the browser with a real model
    dom.window.ClientSearchQueryEmbedder = function (q) {
        return semanticData.query_embeddings[q] || null;
    };
    dom.window.searchIndexUrl = "/search-index.json";
    dom.window.fetch = async function () {
        return { ok: true, json: async function () { return documents; } };
    };
    dom.window.eval(BASE_RUNTIME);
    dom.window.eval(fs.readFileSync(path.join(ADAPTER_DIR, "semantic.js"), "utf8"));
    return dom.window;
}

function createLexicalWindow(query) {
    var indexJson = path.join(FIXTURE_SITE, "_site", "search-index.json");
    if (!fs.existsSync(indexJson)) {
        return null;
    }
    var index = JSON.parse(fs.readFileSync(indexJson, "utf8"));

    var dom = new JSDOM(
        `<!doctype html>
        <form id="search-form"><input id="search-query"><button>Search</button></form>
        <div id="search-status"></div><div id="search-results"></div>`,
        { url: `https://example.com/search/?q=${encodeURIComponent(query)}`, runScripts: "outside-only" }
    );
    dom.window.MiniSearch = MiniSearch;
    dom.window.searchIndexUrl = "/search-index.json";
    dom.window.fetch = async function () {
        return { ok: true, json: async function () { return index; } };
    };
    dom.window.eval(BASE_RUNTIME);
    dom.window.eval(fs.readFileSync(path.join(ADAPTER_DIR, "minisearch.js"), "utf8"));
    return dom.window;
}

var semanticData = loadSemanticIndex();
var hasLexicalIndex = fs.existsSync(path.join(FIXTURE_SITE, "_site", "search-index.json"));

// --- Semantic search quality tests (real Ollama embeddings) ---
//
// These tests use the real Ollama-generated index. They verify that
// the semantic adapter in the browser correctly:
//   1. Filters documents with embeddings
//   2. Computes cosine similarity against the query embedding
//   3. Ranks results by similarity
//   4. Returns the expected articles for concept queries

EXPECTED_RESULTS.forEach(function (expected) {
    var runOrSkip = semanticData ? test : test.skip;

    runOrSkip(`semantic quality: ${expected.description}`, async function () {
        var window = createSemanticWindow(semanticData, expected.query);
        await settle();
        var titles = resultTitles(window);

        assert.ok(titles.length > 0, `semantic search should return results for "${expected.query}"`);

        // Verify expected articles appear in the top 5 results
        expected.expectedInTop5.forEach(function (expectedTitle) {
            var top5 = titles.slice(0, 5);
            assert.ok(
                top5.includes(expectedTitle),
                `"${expectedTitle}" should be in top 5 for "${expected.query}" — got: ${JSON.stringify(top5)}`
            );
        });
    });
});

// --- Lexical vs semantic comparison (real data) ---
//
// For each concept query, verify that semantic search ranks the target
// article higher than lexical search does. This demonstrates the actual
// value of LLM-based search using real embeddings, not mock data.

EXPECTED_RESULTS.forEach(function (expected) {
    var runOrSkip = (semanticData && hasLexicalIndex) ? test : test.skip;

    runOrSkip(`comparison: ${expected.description} — semantic vs lexical ranking`, async function () {
        // Semantic
        var semWindow = createSemanticWindow(semanticData, expected.query);
        await settle();
        var semTitles = resultTitles(semWindow);

        // Lexical
        var lexWindow = createLexicalWindow(expected.query);
        await settle();
        var lexTitles = lexWindow ? resultTitles(lexWindow) : [];

        // Semantic should find the expected article
        expected.expectedInTop5.forEach(function (expectedTitle) {
            assert.ok(
                semTitles.slice(0, 5).includes(expectedTitle),
                `semantic should rank "${expectedTitle}" in top 5 for "${expected.query}"`
            );
        });

        // Compare ranking positions — semantic should rank target higher
        // than lexical (or lexical doesn't find it at all)
        expected.expectedInTop5.forEach(function (expectedTitle) {
            var semRank = semTitles.indexOf(expectedTitle);
            var lexRank = lexTitles.indexOf(expectedTitle);

            if (lexRank >= 0) {
                assert.ok(
                    semRank <= lexRank,
                    `semantic should rank "${expectedTitle}" (position ${semRank + 1}) ` +
                    `at least as high as lexical (position ${lexRank + 1}) for "${expected.query}"`
                );
            }
            // If lexRank is -1, lexical didn't find it — semantic advantage is clear
        });
    });
});
