# frozen_string_literal: true

require "cgi/escape"
require "json"
require "jekyll"
require "pathname"
require "time"
require_relative "client_search/version"
require_relative "client_search/embedding_configuration"
require_relative "client_search/live_search_configuration"
require_relative "client_search/related_configuration"
require_relative "client_search/dropdown_configuration"
require_relative "client_search/query_embedder_configuration"
require_relative "client_search/configuration_accessors"
require_relative "client_search/configuration"
require_relative "client_search/document_builder"
require_relative "client_search/search_index_page"
require_relative "client_search/runtime_config_page"
require_relative "client_search/related_analyzer"
require_relative "client_search/related_page"
require_relative "client_search/embedder_config_page"
require_relative "client_search/index_cache"
require_relative "client_search/ollama_embedding_adapter"
require_relative "client_search/generator"
require_relative "client_search/related_tag"
require_relative "client_search/dropdown_tag"
require_relative "client_search/search_tag"
